packages:
    github.com/JoePeach762/PP_project/user_service/internal/services/user:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            outpkg: "mocks"
            filename: "{{.InterfaceName | snakecase }}.go"
            include-regex: "^(userStorage|statsStorage)$"
            all: True
            exported: True
            mockname: "{{.InterfaceName | firstUpper }}"
