// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/meal_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	WeightGrams   float32                `protobuf:"fixed32,4,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"`
	Calories_100G float32                `protobuf:"fixed32,5,opt,name=calories_100g,json=calories100g,proto3" json:"calories_100g,omitempty"`
	Proteins_100G float32                `protobuf:"fixed32,6,opt,name=proteins_100g,json=proteins100g,proto3" json:"proteins_100g,omitempty"`
	Fats_100G     float32                `protobuf:"fixed32,7,opt,name=fats_100g,json=fats100g,proto3" json:"fats_100g,omitempty"`
	Carbs_100G    float32                `protobuf:"fixed32,8,opt,name=carbs_100g,json=carbs100g,proto3" json:"carbs_100g,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealInfo) Reset() {
	*x = MealInfo{}
	mi := &file_models_meal_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealInfo) ProtoMessage() {}

func (x *MealInfo) ProtoReflect() protoreflect.Message {
	mi := &file_models_meal_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealInfo.ProtoReflect.Descriptor instead.
func (*MealInfo) Descriptor() ([]byte, []int) {
	return file_models_meal_model_proto_rawDescGZIP(), []int{0}
}

func (x *MealInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MealInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MealInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealInfo) GetWeightGrams() float32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

func (x *MealInfo) GetCalories_100G() float32 {
	if x != nil {
		return x.Calories_100G
	}
	return 0
}

func (x *MealInfo) GetProteins_100G() float32 {
	if x != nil {
		return x.Proteins_100G
	}
	return 0
}

func (x *MealInfo) GetFats_100G() float32 {
	if x != nil {
		return x.Fats_100G
	}
	return 0
}

func (x *MealInfo) GetCarbs_100G() float32 {
	if x != nil {
		return x.Carbs_100G
	}
	return 0
}

func (x *MealInfo) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

var File_models_meal_model_proto protoreflect.FileDescriptor

const file_models_meal_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/meal_model.proto\x12\x0fmeals.models.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\bMealInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fweight_grams\x18\x04 \x01(\x02R\vweightGrams\x12#\n" +
	"\rcalories_100g\x18\x05 \x01(\x02R\fcalories100g\x12#\n" +
	"\rproteins_100g\x18\x06 \x01(\x02R\fproteins100g\x12\x1b\n" +
	"\tfats_100g\x18\a \x01(\x02R\bfats100g\x12\x1d\n" +
	"\n" +
	"carbs_100g\x18\b \x01(\x02R\tcarbs100g\x12.\n" +
	"\x04date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x04dateB6Z4github.com/JoePeach762/PP_project/internal/pb/modelsb\x06proto3"

var (
	file_models_meal_model_proto_rawDescOnce sync.Once
	file_models_meal_model_proto_rawDescData []byte
)

func file_models_meal_model_proto_rawDescGZIP() []byte {
	file_models_meal_model_proto_rawDescOnce.Do(func() {
		file_models_meal_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_meal_model_proto_rawDesc), len(file_models_meal_model_proto_rawDesc)))
	})
	return file_models_meal_model_proto_rawDescData
}

var file_models_meal_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_meal_model_proto_goTypes = []any{
	(*MealInfo)(nil),              // 0: meals.models.v1.MealInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_models_meal_model_proto_depIdxs = []int32{
	1, // 0: meals.models.v1.MealInfo.date:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_meal_model_proto_init() }
func file_models_meal_model_proto_init() {
	if File_models_meal_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_meal_model_proto_rawDesc), len(file_models_meal_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_meal_model_proto_goTypes,
		DependencyIndexes: file_models_meal_model_proto_depIdxs,
		MessageInfos:      file_models_meal_model_proto_msgTypes,
	}.Build()
	File_models_meal_model_proto = out.File
	file_models_meal_model_proto_goTypes = nil
	file_models_meal_model_proto_depIdxs = nil
}
