// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/JoePeach762/PP_project/user_service/internal/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// StatsStorage is an autogenerated mock type for the statsStorage type
type StatsStorage struct {
	mock.Mock
}

type StatsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *StatsStorage) EXPECT() *StatsStorage_Expecter {
	return &StatsStorage_Expecter{mock: &_m.Mock}
}

// AddMealToUser provides a mock function with given fields: ctx, mealInfo
func (_m *StatsStorage) AddMealToUser(ctx context.Context, mealInfo *models.MealInfo) error {
	ret := _m.Called(ctx, mealInfo)

	if len(ret) == 0 {
		panic("no return value specified for AddMealToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MealInfo) error); ok {
		r0 = rf(ctx, mealInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StatsStorage_AddMealToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMealToUser'
type StatsStorage_AddMealToUser_Call struct {
	*mock.Call
}

// AddMealToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - mealInfo *models.MealInfo
func (_e *StatsStorage_Expecter) AddMealToUser(ctx interface{}, mealInfo interface{}) *StatsStorage_AddMealToUser_Call {
	return &StatsStorage_AddMealToUser_Call{Call: _e.mock.On("AddMealToUser", ctx, mealInfo)}
}

func (_c *StatsStorage_AddMealToUser_Call) Run(run func(ctx context.Context, mealInfo *models.MealInfo)) *StatsStorage_AddMealToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.MealInfo))
	})
	return _c
}

func (_c *StatsStorage_AddMealToUser_Call) Return(_a0 error) *StatsStorage_AddMealToUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StatsStorage_AddMealToUser_Call) RunAndReturn(run func(context.Context, *models.MealInfo) error) *StatsStorage_AddMealToUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatsByUserIDs provides a mock function with given fields: ctx, ids, date
func (_m *StatsStorage) GetStatsByUserIDs(ctx context.Context, ids []uint64, date time.Time) ([]*models.UserStats, error) {
	ret := _m.Called(ctx, ids, date)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsByUserIDs")
	}

	var r0 []*models.UserStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64, time.Time) ([]*models.UserStats, error)); ok {
		return rf(ctx, ids, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64, time.Time) []*models.UserStats); ok {
		r0 = rf(ctx, ids, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64, time.Time) error); ok {
		r1 = rf(ctx, ids, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StatsStorage_GetStatsByUserIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsByUserIDs'
type StatsStorage_GetStatsByUserIDs_Call struct {
	*mock.Call
}

// GetStatsByUserIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint64
//   - date time.Time
func (_e *StatsStorage_Expecter) GetStatsByUserIDs(ctx interface{}, ids interface{}, date interface{}) *StatsStorage_GetStatsByUserIDs_Call {
	return &StatsStorage_GetStatsByUserIDs_Call{Call: _e.mock.On("GetStatsByUserIDs", ctx, ids, date)}
}

func (_c *StatsStorage_GetStatsByUserIDs_Call) Run(run func(ctx context.Context, ids []uint64, date time.Time)) *StatsStorage_GetStatsByUserIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64), args[2].(time.Time))
	})
	return _c
}

func (_c *StatsStorage_GetStatsByUserIDs_Call) Return(_a0 []*models.UserStats, _a1 error) *StatsStorage_GetStatsByUserIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StatsStorage_GetStatsByUserIDs_Call) RunAndReturn(run func(context.Context, []uint64, time.Time) ([]*models.UserStats, error)) *StatsStorage_GetStatsByUserIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewStatsStorage creates a new instance of StatsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsStorage {
	mock := &StatsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
