// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/JoePeach762/PP_project/user_service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// UserStorage is an autogenerated mock type for the userStorage type
type UserStorage struct {
	mock.Mock
}

type UserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *UserStorage) EXPECT() *UserStorage_Expecter {
	return &UserStorage_Expecter{mock: &_m.Mock}
}

// AddUsers provides a mock function with given fields: ctx, infos
func (_m *UserStorage) AddUsers(ctx context.Context, infos []*models.UserInfo) error {
	ret := _m.Called(ctx, infos)

	if len(ret) == 0 {
		panic("no return value specified for AddUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.UserInfo) error); ok {
		r0 = rf(ctx, infos)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserStorage_AddUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUsers'
type UserStorage_AddUsers_Call struct {
	*mock.Call
}

// AddUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - infos []*models.UserInfo
func (_e *UserStorage_Expecter) AddUsers(ctx interface{}, infos interface{}) *UserStorage_AddUsers_Call {
	return &UserStorage_AddUsers_Call{Call: _e.mock.On("AddUsers", ctx, infos)}
}

func (_c *UserStorage_AddUsers_Call) Run(run func(ctx context.Context, infos []*models.UserInfo)) *UserStorage_AddUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.UserInfo))
	})
	return _c
}

func (_c *UserStorage_AddUsers_Call) Return(_a0 error) *UserStorage_AddUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserStorage_AddUsers_Call) RunAndReturn(run func(context.Context, []*models.UserInfo) error) *UserStorage_AddUsers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUsers provides a mock function with given fields: ctx, ids
func (_m *UserStorage) DeleteUsers(ctx context.Context, ids []uint64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUsers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserStorage_DeleteUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUsers'
type UserStorage_DeleteUsers_Call struct {
	*mock.Call
}

// DeleteUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint64
func (_e *UserStorage_Expecter) DeleteUsers(ctx interface{}, ids interface{}) *UserStorage_DeleteUsers_Call {
	return &UserStorage_DeleteUsers_Call{Call: _e.mock.On("DeleteUsers", ctx, ids)}
}

func (_c *UserStorage_DeleteUsers_Call) Run(run func(ctx context.Context, ids []uint64)) *UserStorage_DeleteUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *UserStorage_DeleteUsers_Call) Return(_a0 error) *UserStorage_DeleteUsers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserStorage_DeleteUsers_Call) RunAndReturn(run func(context.Context, []uint64) error) *UserStorage_DeleteUsers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUsersAndEnqueueEvent provides a mock function with given fields: ctx, ids
func (_m *UserStorage) DeleteUsersAndEnqueueEvent(ctx context.Context, ids []uint64) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUsersAndEnqueueEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserStorage_DeleteUsersAndEnqueueEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUsersAndEnqueueEvent'
type UserStorage_DeleteUsersAndEnqueueEvent_Call struct {
	*mock.Call
}

// DeleteUsersAndEnqueueEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint64
func (_e *UserStorage_Expecter) DeleteUsersAndEnqueueEvent(ctx interface{}, ids interface{}) *UserStorage_DeleteUsersAndEnqueueEvent_Call {
	return &UserStorage_DeleteUsersAndEnqueueEvent_Call{Call: _e.mock.On("DeleteUsersAndEnqueueEvent", ctx, ids)}
}

func (_c *UserStorage_DeleteUsersAndEnqueueEvent_Call) Run(run func(ctx context.Context, ids []uint64)) *UserStorage_DeleteUsersAndEnqueueEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *UserStorage_DeleteUsersAndEnqueueEvent_Call) Return(_a0 error) *UserStorage_DeleteUsersAndEnqueueEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserStorage_DeleteUsersAndEnqueueEvent_Call) RunAndReturn(run func(context.Context, []uint64) error) *UserStorage_DeleteUsersAndEnqueueEvent_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersByIds provides a mock function with given fields: ctx, ids
func (_m *UserStorage) GetUsersByIds(ctx context.Context, ids []uint64) ([]*models.UserInfo, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersByIds")
	}

	var r0 []*models.UserInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.UserInfo, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.UserInfo); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserStorage_GetUsersByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersByIds'
type UserStorage_GetUsersByIds_Call struct {
	*mock.Call
}

// GetUsersByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint64
func (_e *UserStorage_Expecter) GetUsersByIds(ctx interface{}, ids interface{}) *UserStorage_GetUsersByIds_Call {
	return &UserStorage_GetUsersByIds_Call{Call: _e.mock.On("GetUsersByIds", ctx, ids)}
}

func (_c *UserStorage_GetUsersByIds_Call) Run(run func(ctx context.Context, ids []uint64)) *UserStorage_GetUsersByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *UserStorage_GetUsersByIds_Call) Return(_a0 []*models.UserInfo, _a1 error) *UserStorage_GetUsersByIds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserStorage_GetUsersByIds_Call) RunAndReturn(run func(context.Context, []uint64) ([]*models.UserInfo, error)) *UserStorage_GetUsersByIds_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, id, info
func (_m *UserStorage) UpdateUser(ctx context.Context, id uint64, info models.UserInfo) error {
	ret := _m.Called(ctx, id, info)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, models.UserInfo) error); ok {
		r0 = rf(ctx, id, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserStorage_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type UserStorage_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
//   - info models.UserInfo
func (_e *UserStorage_Expecter) UpdateUser(ctx interface{}, id interface{}, info interface{}) *UserStorage_UpdateUser_Call {
	return &UserStorage_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, info)}
}

func (_c *UserStorage_UpdateUser_Call) Run(run func(ctx context.Context, id uint64, info models.UserInfo)) *UserStorage_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(models.UserInfo))
	})
	return _c
}

func (_c *UserStorage_UpdateUser_Call) Return(_a0 error) *UserStorage_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserStorage_UpdateUser_Call) RunAndReturn(run func(context.Context, uint64, models.UserInfo) error) *UserStorage_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserStorage creates a new instance of UserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserStorage {
	mock := &UserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
