// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: meal_api/meals.proto

package meals_api

import (
	models "github.com/JoePeach762/PP_project/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WeightGrams   float32                `protobuf:"fixed32,2,opt,name=weight_grams,json=weightGrams,proto3" json:"weight_grams,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMealRequest) Reset() {
	*x = AddMealRequest{}
	mi := &file_meal_api_meals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMealRequest) ProtoMessage() {}

func (x *AddMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meal_api_meals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMealRequest.ProtoReflect.Descriptor instead.
func (*AddMealRequest) Descriptor() ([]byte, []int) {
	return file_meal_api_meals_proto_rawDescGZIP(), []int{0}
}

func (x *AddMealRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddMealRequest) GetWeightGrams() float32 {
	if x != nil {
		return x.WeightGrams
	}
	return 0
}

func (x *AddMealRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsRequest) Reset() {
	*x = GetMealsRequest{}
	mi := &file_meal_api_meals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsRequest) ProtoMessage() {}

func (x *GetMealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meal_api_meals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsRequest.ProtoReflect.Descriptor instead.
func (*GetMealsRequest) Descriptor() ([]byte, []int) {
	return file_meal_api_meals_proto_rawDescGZIP(), []int{1}
}

func (x *GetMealsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meals         []*models.MealInfo     `protobuf:"bytes,1,rep,name=meals,proto3" json:"meals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsResponse) Reset() {
	*x = GetMealsResponse{}
	mi := &file_meal_api_meals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsResponse) ProtoMessage() {}

func (x *GetMealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meal_api_meals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsResponse.ProtoReflect.Descriptor instead.
func (*GetMealsResponse) Descriptor() ([]byte, []int) {
	return file_meal_api_meals_proto_rawDescGZIP(), []int{2}
}

func (x *GetMealsResponse) GetMeals() []*models.MealInfo {
	if x != nil {
		return x.Meals
	}
	return nil
}

var File_meal_api_meals_proto protoreflect.FileDescriptor

const file_meal_api_meals_proto_rawDesc = "" +
	"\n" +
	"\x14meal_api/meals.proto\x12\x10meals.service.v1\x1a\x17models/meal_model.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"`\n" +
	"\x0eAddMealRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fweight_grams\x18\x02 \x01(\x02R\vweightGrams\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\"*\n" +
	"\x0fGetMealsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"C\n" +
	"\x10GetMealsResponse\x12/\n" +
	"\x05meals\x18\x01 \x03(\v2\x19.meals.models.v1.MealInfoR\x05meals2\xce\x01\n" +
	"\vMealService\x12Y\n" +
	"\aAddMeal\x12 .meals.service.v1.AddMealRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/meals\x12d\n" +
	"\bGetMeals\x12!.meals.service.v1.GetMealsRequest\x1a\".meals.service.v1.GetMealsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/mealsB9Z7github.com/JoePeach762/PP_project/internal/pb/meals_apib\x06proto3"

var (
	file_meal_api_meals_proto_rawDescOnce sync.Once
	file_meal_api_meals_proto_rawDescData []byte
)

func file_meal_api_meals_proto_rawDescGZIP() []byte {
	file_meal_api_meals_proto_rawDescOnce.Do(func() {
		file_meal_api_meals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meal_api_meals_proto_rawDesc), len(file_meal_api_meals_proto_rawDesc)))
	})
	return file_meal_api_meals_proto_rawDescData
}

var file_meal_api_meals_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_meal_api_meals_proto_goTypes = []any{
	(*AddMealRequest)(nil),   // 0: meals.service.v1.AddMealRequest
	(*GetMealsRequest)(nil),  // 1: meals.service.v1.GetMealsRequest
	(*GetMealsResponse)(nil), // 2: meals.service.v1.GetMealsResponse
	(*models.MealInfo)(nil),  // 3: meals.models.v1.MealInfo
	(*emptypb.Empty)(nil),    // 4: google.protobuf.Empty
}
var file_meal_api_meals_proto_depIdxs = []int32{
	3, // 0: meals.service.v1.GetMealsResponse.meals:type_name -> meals.models.v1.MealInfo
	0, // 1: meals.service.v1.MealService.AddMeal:input_type -> meals.service.v1.AddMealRequest
	1, // 2: meals.service.v1.MealService.GetMeals:input_type -> meals.service.v1.GetMealsRequest
	4, // 3: meals.service.v1.MealService.AddMeal:output_type -> google.protobuf.Empty
	2, // 4: meals.service.v1.MealService.GetMeals:output_type -> meals.service.v1.GetMealsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_meal_api_meals_proto_init() }
func file_meal_api_meals_proto_init() {
	if File_meal_api_meals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meal_api_meals_proto_rawDesc), len(file_meal_api_meals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meal_api_meals_proto_goTypes,
		DependencyIndexes: file_meal_api_meals_proto_depIdxs,
		MessageInfos:      file_meal_api_meals_proto_msgTypes,
	}.Build()
	File_meal_api_meals_proto = out.File
	file_meal_api_meals_proto_goTypes = nil
	file_meal_api_meals_proto_depIdxs = nil
}
