// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: models/user_models/user_model.proto

package user_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Sex             string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Age             uint32                 `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	HeightCm        uint32                 `protobuf:"varint,6,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	WeightKg        uint32                 `protobuf:"varint,7,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	TargetWeightKg  uint32                 `protobuf:"varint,8,opt,name=target_weight_kg,json=targetWeightKg,proto3" json:"target_weight_kg,omitempty"`
	CurrentCalories uint32                 `protobuf:"varint,9,opt,name=current_calories,json=currentCalories,proto3" json:"current_calories,omitempty"`
	CurrentProteins uint32                 `protobuf:"varint,10,opt,name=current_proteins,json=currentProteins,proto3" json:"current_proteins,omitempty"`
	CurrentFats     uint32                 `protobuf:"varint,11,opt,name=current_fats,json=currentFats,proto3" json:"current_fats,omitempty"`
	CurrentCarbs    uint32                 `protobuf:"varint,12,opt,name=current_carbs,json=currentCarbs,proto3" json:"current_carbs,omitempty"`
	TargetCalories  uint32                 `protobuf:"varint,13,opt,name=target_calories,json=targetCalories,proto3" json:"target_calories,omitempty"`
	TargetProteins  uint32                 `protobuf:"varint,14,opt,name=target_proteins,json=targetProteins,proto3" json:"target_proteins,omitempty"`
	TargetFats      uint32                 `protobuf:"varint,15,opt,name=target_fats,json=targetFats,proto3" json:"target_fats,omitempty"`
	TargetCarbs     uint32                 `protobuf:"varint,16,opt,name=target_carbs,json=targetCarbs,proto3" json:"target_carbs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_models_user_models_user_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_models_user_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_models_user_models_user_model_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *UserInfo) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UserInfo) GetHeightCm() uint32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *UserInfo) GetWeightKg() uint32 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *UserInfo) GetTargetWeightKg() uint32 {
	if x != nil {
		return x.TargetWeightKg
	}
	return 0
}

func (x *UserInfo) GetCurrentCalories() uint32 {
	if x != nil {
		return x.CurrentCalories
	}
	return 0
}

func (x *UserInfo) GetCurrentProteins() uint32 {
	if x != nil {
		return x.CurrentProteins
	}
	return 0
}

func (x *UserInfo) GetCurrentFats() uint32 {
	if x != nil {
		return x.CurrentFats
	}
	return 0
}

func (x *UserInfo) GetCurrentCarbs() uint32 {
	if x != nil {
		return x.CurrentCarbs
	}
	return 0
}

func (x *UserInfo) GetTargetCalories() uint32 {
	if x != nil {
		return x.TargetCalories
	}
	return 0
}

func (x *UserInfo) GetTargetProteins() uint32 {
	if x != nil {
		return x.TargetProteins
	}
	return 0
}

func (x *UserInfo) GetTargetFats() uint32 {
	if x != nil {
		return x.TargetFats
	}
	return 0
}

func (x *UserInfo) GetTargetCarbs() uint32 {
	if x != nil {
		return x.TargetCarbs
	}
	return 0
}

var File_models_user_models_user_model_proto protoreflect.FileDescriptor

const file_models_user_models_user_model_proto_rawDesc = "" +
	"\n" +
	"#models/user_models/user_model.proto\x12\x0fusers.models.v1\"\x80\x04\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x10\n" +
	"\x03age\x18\x05 \x01(\rR\x03age\x12\x1b\n" +
	"\theight_cm\x18\x06 \x01(\rR\bheightCm\x12\x1b\n" +
	"\tweight_kg\x18\a \x01(\rR\bweightKg\x12(\n" +
	"\x10target_weight_kg\x18\b \x01(\rR\x0etargetWeightKg\x12)\n" +
	"\x10current_calories\x18\t \x01(\rR\x0fcurrentCalories\x12)\n" +
	"\x10current_proteins\x18\n" +
	" \x01(\rR\x0fcurrentProteins\x12!\n" +
	"\fcurrent_fats\x18\v \x01(\rR\vcurrentFats\x12#\n" +
	"\rcurrent_carbs\x18\f \x01(\rR\fcurrentCarbs\x12'\n" +
	"\x0ftarget_calories\x18\r \x01(\rR\x0etargetCalories\x12'\n" +
	"\x0ftarget_proteins\x18\x0e \x01(\rR\x0etargetProteins\x12\x1f\n" +
	"\vtarget_fats\x18\x0f \x01(\rR\n" +
	"targetFats\x12!\n" +
	"\ftarget_carbs\x18\x10 \x01(\rR\vtargetCarbsBOZMgithub.com/JoePeach762/PP_project/user_service/internal/pb/models/user_modelsb\x06proto3"

var (
	file_models_user_models_user_model_proto_rawDescOnce sync.Once
	file_models_user_models_user_model_proto_rawDescData []byte
)

func file_models_user_models_user_model_proto_rawDescGZIP() []byte {
	file_models_user_models_user_model_proto_rawDescOnce.Do(func() {
		file_models_user_models_user_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_user_models_user_model_proto_rawDesc), len(file_models_user_models_user_model_proto_rawDesc)))
	})
	return file_models_user_models_user_model_proto_rawDescData
}

var file_models_user_models_user_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_user_models_user_model_proto_goTypes = []any{
	(*UserInfo)(nil), // 0: users.models.v1.UserInfo
}
var file_models_user_models_user_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_user_models_user_model_proto_init() }
func file_models_user_models_user_model_proto_init() {
	if File_models_user_models_user_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_user_models_user_model_proto_rawDesc), len(file_models_user_models_user_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_user_models_user_model_proto_goTypes,
		DependencyIndexes: file_models_user_models_user_model_proto_depIdxs,
		MessageInfos:      file_models_user_models_user_model_proto_msgTypes,
	}.Build()
	File_models_user_models_user_model_proto = out.File
	file_models_user_models_user_model_proto_goTypes = nil
	file_models_user_models_user_model_proto_depIdxs = nil
}
