// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: meals_api/meals.proto

package meals_api

import (
	meal_models "github.com/JoePeach762/PP_project/meal_service/internal/pb/models/meal_models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meal          *meal_models.MealInput `protobuf:"bytes,1,opt,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMealRequest) Reset() {
	*x = AddMealRequest{}
	mi := &file_meals_api_meals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMealRequest) ProtoMessage() {}

func (x *AddMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meals_api_meals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMealRequest.ProtoReflect.Descriptor instead.
func (*AddMealRequest) Descriptor() ([]byte, []int) {
	return file_meals_api_meals_proto_rawDescGZIP(), []int{0}
}

func (x *AddMealRequest) GetMeal() *meal_models.MealInput {
	if x != nil {
		return x.Meal
	}
	return nil
}

type GetMealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsRequest) Reset() {
	*x = GetMealsRequest{}
	mi := &file_meals_api_meals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsRequest) ProtoMessage() {}

func (x *GetMealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meals_api_meals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsRequest.ProtoReflect.Descriptor instead.
func (*GetMealsRequest) Descriptor() ([]byte, []int) {
	return file_meals_api_meals_proto_rawDescGZIP(), []int{1}
}

func (x *GetMealsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMealsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Meals         []*meal_models.MealInfo `protobuf:"bytes,1,rep,name=meals,proto3" json:"meals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsResponse) Reset() {
	*x = GetMealsResponse{}
	mi := &file_meals_api_meals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsResponse) ProtoMessage() {}

func (x *GetMealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meals_api_meals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsResponse.ProtoReflect.Descriptor instead.
func (*GetMealsResponse) Descriptor() ([]byte, []int) {
	return file_meals_api_meals_proto_rawDescGZIP(), []int{2}
}

func (x *GetMealsResponse) GetMeals() []*meal_models.MealInfo {
	if x != nil {
		return x.Meals
	}
	return nil
}

type DeleteMealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint64               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMealsRequest) Reset() {
	*x = DeleteMealsRequest{}
	mi := &file_meals_api_meals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMealsRequest) ProtoMessage() {}

func (x *DeleteMealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meals_api_meals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMealsRequest.ProtoReflect.Descriptor instead.
func (*DeleteMealsRequest) Descriptor() ([]byte, []int) {
	return file_meals_api_meals_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMealsRequest) GetUserIds() []uint64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type DeleteMealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMealsResponse) Reset() {
	*x = DeleteMealsResponse{}
	mi := &file_meals_api_meals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMealsResponse) ProtoMessage() {}

func (x *DeleteMealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meals_api_meals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMealsResponse.ProtoReflect.Descriptor instead.
func (*DeleteMealsResponse) Descriptor() ([]byte, []int) {
	return file_meals_api_meals_proto_rawDescGZIP(), []int{4}
}

var File_meals_api_meals_proto protoreflect.FileDescriptor

const file_meals_api_meals_proto_rawDesc = "" +
	"\n" +
	"\x15meals_api/meals.proto\x12\x10meals.service.v1\x1a#models/meal_models/meal_model.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"@\n" +
	"\x0eAddMealRequest\x12.\n" +
	"\x04meal\x18\x01 \x01(\v2\x1a.meals.models.v1.MealInputR\x04meal\"*\n" +
	"\x0fGetMealsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"C\n" +
	"\x10GetMealsResponse\x12/\n" +
	"\x05meals\x18\x01 \x03(\v2\x19.meals.models.v1.MealInfoR\x05meals\"/\n" +
	"\x12DeleteMealsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x04R\auserIds\"\x15\n" +
	"\x13DeleteMealsResponse2\xc8\x02\n" +
	"\vMealService\x12Y\n" +
	"\aAddMeal\x12 .meals.service.v1.AddMealRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/meals\x12d\n" +
	"\bGetMeals\x12!.meals.service.v1.GetMealsRequest\x1a\".meals.service.v1.GetMealsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/meals\x12x\n" +
	"\vDeleteMeals\x12$.meals.service.v1.DeleteMealsRequest\x1a%.meals.service.v1.DeleteMealsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/meals/{user_ids}BFZDgithub.com/JoePeach762/PP_project/meal_service/internal/pb/meals_apib\x06proto3"

var (
	file_meals_api_meals_proto_rawDescOnce sync.Once
	file_meals_api_meals_proto_rawDescData []byte
)

func file_meals_api_meals_proto_rawDescGZIP() []byte {
	file_meals_api_meals_proto_rawDescOnce.Do(func() {
		file_meals_api_meals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meals_api_meals_proto_rawDesc), len(file_meals_api_meals_proto_rawDesc)))
	})
	return file_meals_api_meals_proto_rawDescData
}

var file_meals_api_meals_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_meals_api_meals_proto_goTypes = []any{
	(*AddMealRequest)(nil),        // 0: meals.service.v1.AddMealRequest
	(*GetMealsRequest)(nil),       // 1: meals.service.v1.GetMealsRequest
	(*GetMealsResponse)(nil),      // 2: meals.service.v1.GetMealsResponse
	(*DeleteMealsRequest)(nil),    // 3: meals.service.v1.DeleteMealsRequest
	(*DeleteMealsResponse)(nil),   // 4: meals.service.v1.DeleteMealsResponse
	(*meal_models.MealInput)(nil), // 5: meals.models.v1.MealInput
	(*meal_models.MealInfo)(nil),  // 6: meals.models.v1.MealInfo
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_meals_api_meals_proto_depIdxs = []int32{
	5, // 0: meals.service.v1.AddMealRequest.meal:type_name -> meals.models.v1.MealInput
	6, // 1: meals.service.v1.GetMealsResponse.meals:type_name -> meals.models.v1.MealInfo
	0, // 2: meals.service.v1.MealService.AddMeal:input_type -> meals.service.v1.AddMealRequest
	1, // 3: meals.service.v1.MealService.GetMeals:input_type -> meals.service.v1.GetMealsRequest
	3, // 4: meals.service.v1.MealService.DeleteMeals:input_type -> meals.service.v1.DeleteMealsRequest
	7, // 5: meals.service.v1.MealService.AddMeal:output_type -> google.protobuf.Empty
	2, // 6: meals.service.v1.MealService.GetMeals:output_type -> meals.service.v1.GetMealsResponse
	4, // 7: meals.service.v1.MealService.DeleteMeals:output_type -> meals.service.v1.DeleteMealsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_meals_api_meals_proto_init() }
func file_meals_api_meals_proto_init() {
	if File_meals_api_meals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meals_api_meals_proto_rawDesc), len(file_meals_api_meals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meals_api_meals_proto_goTypes,
		DependencyIndexes: file_meals_api_meals_proto_depIdxs,
		MessageInfos:      file_meals_api_meals_proto_msgTypes,
	}.Build()
	File_meals_api_meals_proto = out.File
	file_meals_api_meals_proto_goTypes = nil
	file_meals_api_meals_proto_depIdxs = nil
}
