// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: users_api/users.proto

package users_api

import (
	user_models "github.com/JoePeach762/PP_project/user_service/internal/pb/models/user_models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUsersRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Users         []*user_models.UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsersRequest) Reset() {
	*x = CreateUsersRequest{}
	mi := &file_users_api_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsersRequest) ProtoMessage() {}

func (x *CreateUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsersRequest.ProtoReflect.Descriptor instead.
func (*CreateUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUsersRequest) GetUsers() []*user_models.UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsersResponse) Reset() {
	*x = CreateUsersResponse{}
	mi := &file_users_api_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsersResponse) ProtoMessage() {}

func (x *CreateUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsersResponse.ProtoReflect.Descriptor instead.
func (*CreateUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{1}
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *user_models.UserInfo  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_users_api_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetUser() *user_models.UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_users_api_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{3}
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_users_api_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{4}
}

func (x *GetUsersRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetUsersResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Users         []*user_models.UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_users_api_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{5}
}

func (x *GetUsersResponse) GetUsers() []*user_models.UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type DeleteUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersRequest) Reset() {
	*x = DeleteUsersRequest{}
	mi := &file_users_api_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersRequest) ProtoMessage() {}

func (x *DeleteUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersRequest.ProtoReflect.Descriptor instead.
func (*DeleteUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUsersRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersResponse) Reset() {
	*x = DeleteUsersResponse{}
	mi := &file_users_api_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersResponse) ProtoMessage() {}

func (x *DeleteUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_api_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersResponse.ProtoReflect.Descriptor instead.
func (*DeleteUsersResponse) Descriptor() ([]byte, []int) {
	return file_users_api_users_proto_rawDescGZIP(), []int{7}
}

var File_users_api_users_proto protoreflect.FileDescriptor

const file_users_api_users_proto_rawDesc = "" +
	"\n" +
	"\x15users_api/users.proto\x12\x10users.service.v1\x1a#models/user_models/user_model.proto\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\x12CreateUsersRequest\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.users.models.v1.UserInfoR\x05users\"\x15\n" +
	"\x13CreateUsersResponse\"B\n" +
	"\x11UpdateUserRequest\x12-\n" +
	"\x04user\x18\x01 \x01(\v2\x19.users.models.v1.UserInfoR\x04user\"\x14\n" +
	"\x12UpdateUserResponse\"#\n" +
	"\x0fGetUsersRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"C\n" +
	"\x10GetUsersResponse\x12/\n" +
	"\x05users\x18\x01 \x03(\v2\x19.users.models.v1.UserInfoR\x05users\"&\n" +
	"\x12DeleteUsersRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"\x15\n" +
	"\x13DeleteUsersResponse2\xd3\x03\n" +
	"\vUserService\x12p\n" +
	"\vCreateUsers\x12$.users.service.v1.CreateUsersRequest\x1a%.users.service.v1.CreateUsersResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12w\n" +
	"\n" +
	"UpdateUser\x12#.users.service.v1.UpdateUserRequest\x1a$.users.service.v1.UpdateUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*2\x13/v1/users/{user.id}\x12d\n" +
	"\bGetUsers\x12!.users.service.v1.GetUsersRequest\x1a\".users.service.v1.GetUsersResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12s\n" +
	"\vDeleteUsers\x12$.users.service.v1.DeleteUsersRequest\x1a%.users.service.v1.DeleteUsersResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/users/{ids}BFZDgithub.com/JoePeach762/PP_project/user_service/internal/pb/users_apib\x06proto3"

var (
	file_users_api_users_proto_rawDescOnce sync.Once
	file_users_api_users_proto_rawDescData []byte
)

func file_users_api_users_proto_rawDescGZIP() []byte {
	file_users_api_users_proto_rawDescOnce.Do(func() {
		file_users_api_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_api_users_proto_rawDesc), len(file_users_api_users_proto_rawDesc)))
	})
	return file_users_api_users_proto_rawDescData
}

var file_users_api_users_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_users_api_users_proto_goTypes = []any{
	(*CreateUsersRequest)(nil),   // 0: users.service.v1.CreateUsersRequest
	(*CreateUsersResponse)(nil),  // 1: users.service.v1.CreateUsersResponse
	(*UpdateUserRequest)(nil),    // 2: users.service.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),   // 3: users.service.v1.UpdateUserResponse
	(*GetUsersRequest)(nil),      // 4: users.service.v1.GetUsersRequest
	(*GetUsersResponse)(nil),     // 5: users.service.v1.GetUsersResponse
	(*DeleteUsersRequest)(nil),   // 6: users.service.v1.DeleteUsersRequest
	(*DeleteUsersResponse)(nil),  // 7: users.service.v1.DeleteUsersResponse
	(*user_models.UserInfo)(nil), // 8: users.models.v1.UserInfo
}
var file_users_api_users_proto_depIdxs = []int32{
	8, // 0: users.service.v1.CreateUsersRequest.users:type_name -> users.models.v1.UserInfo
	8, // 1: users.service.v1.UpdateUserRequest.user:type_name -> users.models.v1.UserInfo
	8, // 2: users.service.v1.GetUsersResponse.users:type_name -> users.models.v1.UserInfo
	0, // 3: users.service.v1.UserService.CreateUsers:input_type -> users.service.v1.CreateUsersRequest
	2, // 4: users.service.v1.UserService.UpdateUser:input_type -> users.service.v1.UpdateUserRequest
	4, // 5: users.service.v1.UserService.GetUsers:input_type -> users.service.v1.GetUsersRequest
	6, // 6: users.service.v1.UserService.DeleteUsers:input_type -> users.service.v1.DeleteUsersRequest
	1, // 7: users.service.v1.UserService.CreateUsers:output_type -> users.service.v1.CreateUsersResponse
	3, // 8: users.service.v1.UserService.UpdateUser:output_type -> users.service.v1.UpdateUserResponse
	5, // 9: users.service.v1.UserService.GetUsers:output_type -> users.service.v1.GetUsersResponse
	7, // 10: users.service.v1.UserService.DeleteUsers:output_type -> users.service.v1.DeleteUsersResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_users_api_users_proto_init() }
func file_users_api_users_proto_init() {
	if File_users_api_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_api_users_proto_rawDesc), len(file_users_api_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_api_users_proto_goTypes,
		DependencyIndexes: file_users_api_users_proto_depIdxs,
		MessageInfos:      file_users_api_users_proto_msgTypes,
	}.Build()
	File_users_api_users_proto = out.File
	file_users_api_users_proto_goTypes = nil
	file_users_api_users_proto_depIdxs = nil
}
